#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := Sensorstation
	
export IDF_PATH=/media/marc/HOME/home/docs/studium/17HS/CAOS/weatherstation/tools/sensorstation/esp-idf
include $(IDF_PATH)/make/project.mk

